// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {//gradle脚本需要的依赖
    
    repositories {//配置远程仓库
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        mavenCentral()
        maven {url 'https://developer.huawei.com/repo/'}//添加华为依赖，极光需要
    }
    dependencies {//配置构建工具
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'com.google.gms:google-services:4.0.1'  //这行对谷歌服务库进行依赖
        classpath 'com.huawei.agconnect:agcp:1.9.1.301'   //添加华为依赖，极光需要
    }
}

allprojects {//项目本身需要的依赖
    repositories {//配置远程仓库
        google()
        jcenter()
        //需要添加的部分
        maven { url 'https://jitpack.io' }
        mavenCentral()
        maven {url 'https://developer.huawei.com/repo/'}//添加华为依赖，极光需要
    }
}

//运行gradle clean时，执行此处定义的task任务，
// 该任务继承自Delete，删除根目录中的build目录。
task clean(type: Delete) {
    delete rootProject.buildDir
}
