/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer */

#ifndef _Included_com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
#define _Included_com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
 * Method:    startPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_android_1study_1demo_1project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer_startPush
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
 * Method:    stopPush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_android_1study_1demo_1project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer_stopPush
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_android_1study_1demo_1project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer_release
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
 * Method:    setVideoOptions
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_android_1study_1demo_1project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer_setVideoOptions
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
 * Method:    setAudioOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_android_1study_1demo_1project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer_setAudioOptions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
 * Method:    sendVideoPacket
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_example_android_1study_1demo_1project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer_sendVideoPacket
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_android_study_demo_project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer
 * Method:    sendAudioPacket
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_example_android_1study_1demo_1project_opencv_ffmpegUsage_livingStream_FFmpegLiveStreamNativePlayer_sendAudioPacket
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
