/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_study_demo_project_JNI_DataModel */

#ifndef _Included_com_example_android_study_demo_project_JNI_DataModel
#define _Included_com_example_android_study_demo_project_JNI_DataModel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
