/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_study_demo_project_opencv_ffmpegUsage_videoDecoder_FFmpegVideoDecoderNativePlayer */

#ifndef _Included_com_example_android_study_demo_project_opencv_ffmpegUsage_videoDecoder_FFmpegVideoDecoderNativePlayer
#define _Included_com_example_android_study_demo_project_opencv_ffmpegUsage_videoDecoder_FFmpegVideoDecoderNativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_study_demo_project_opencv_ffmpegUsage_videoDecoder_FFmpegVideoDecoderNativePlayer
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_1study_1demo_1project_opencv_ffmpegUsage_videoDecoder_FFmpegVideoDecoderNativePlayer_playVideo
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
