apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"


    defaultConfig {
        applicationId "com.example.android_study_demo_project"
        minSdkVersion 28
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            //设置支持的SO库架构（开发者可以根据需要，选择一个或多个平台的so）
            abiFilters "armeabi", "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        targetCompatibility = 1.8
        sourceCompatibility = 1.8
    }

    //布局文件资源来源
    sourceSets {
        main {
            res.srcDirs = [
                    'src/main/res',
                    'src/main/res/layout',
                    'src/main/res/layout/storageLayout',
                    'src/main/res/layout/fragmentUsageLayout',
                    'src/main/res/layout/mediaLayout',
                    'src/main/res/layout/imageUsageLayout',
            ]
        }
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    //RecyclerView布局插件
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    //卡片布局
    //noinspection GradleCompatible
    implementation 'com.android.support:cardview-v7:24.0.0-alpha1'

    //RXJava插件
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava3:2.9.0'
    //GSon插件
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    //引入glide图片加载库
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    //3D地图
//    implementation 'com.amap.api:3dmap:9.0.0'
    //定位功能
//    implementation 'com.amap.api:location:6.1.0'
    //搜索功能
//    implementation 'com.amap.api:search:9.2.0'
    //导航sdk
    implementation 'com.amap.api:navi-3dmap:9.3.0_3dmap9.3.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'

    //Room插件
    def room_version = '2.2.0-alpha01'
    implementation "androidx.room:room-runtime:$room_version"//Room的api支持
    annotationProcessor "androidx.room:room-compiler:$room_version"//Room的注释处理器

    //Material Design引用
    implementation 'com.google.android.material:material:1.0.0'
    //七牛云SDK
    implementation ('com.qiniu:qiniu-android-sdk:8.5.0'){
        exclude (group: 'com.squareup.okhttp3', module: 'okhttp')
    }
    implementation 'com.qiniu:qiniu-java-sdk:7.2.+'
}
