apply plugin: 'com.android.application'
//极光华为配置需要，启用 华为gradle 插件
apply plugin: 'com.huawei.agconnect'

android {
    //配置签名证书
    //自动化打包设置
    signingConfigs {
        debug {//开发环境
            storeFile file('../androidStudyDemo.jks')//文件所在路径
            storePassword 'feng,123,456'
            keyAlias 'androidStudyDemo'
            keyPassword 'feng,123,456'
        }
        release {//线上模式
            //将密码等放在gradle.properties文件下
            storeFile file(RELEASE_STORE_FILE)
            storePassword RELEASE_STORE_PASSWORD
            keyAlias RELEASE_KEY_ALIAS
            keyPassword RELEASE_KEY_PASSWORD
        }
    }

    compileSdkVersion 30//编译时用的Android版本
    buildToolsVersion "30.0.2"//编译时使用的构建工具的版本（Android Studio3.0后去除此项配置）

    defaultConfig {//设置编译时用的Android版本
        applicationId "com.example.android_study_demo_project"
        minSdkVersion 28
        targetSdkVersion 30
        versionCode 1//版本号
        versionName "1.0"//版本名称，展示在应用市场

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"//使用AndroidJUnitRunner进行单元测试
        ndk {
            //设置支持的SO库架构（开发者可以根据需要，选择一个或多个平台的so）
            abiFilters "armeabi", "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        //数据的个性化配置
        //极光得数据个性化配置
        manifestPlaceholders = [
                JPUSH_PKGNAME : applicationId,
                JPUSH_APPKEY : "2ca7c93834e9e8dc85958064", //JPush 上注册的包名对应的 Appkey.
                JPUSH_CHANNEL : "developer-default", //暂时填写默认值即可.
//                HUAWEI_APPKEY : "MZ-魅族的APPKEY",
//                HUAWEI_APPID : "MZ-魅族的APPID",
//                MEIZU_APPKEY : "MZ-魅族的APPKEY",
//                MEIZU_APPID : "MZ-魅族的APPID",
//                XIAOMI_APPID : "小米的APPID",//JPush5.5.3开始，可以不添加MI-前缀.
//                XIAOMI_APPKEY : "小米的APPKEY",//JPush5.5.3开始，可以不添加MI-前缀.
//                OPPO_APPKEY : "OP-oppo的APPKEY",
//                OPPO_APPID : "OP-oppo的APPID",
//                OPPO_APPSECRET : "OP-oppo的APPSECRET",
//                VIVO_APPKEY : "vivo的APPKEY",
//                VIVO_APPID : "vivo的APPID"
        ]
    }

    buildTypes {//生成、测试环境配置
        release {
            minifyEnabled true//是否对代码进行混淆
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'//指定混淆的规则文件
            signingConfig signingConfigs.release//设置签名信息
        }
        debug {
            minifyEnabled false//是否对代码进行混淆
            signingConfig signingConfigs.release
        }
    }
    compileOptions {//指定 Java 编译器在编译项目源代码时所使用的语言级别和编码格式等选项
        targetCompatibility = 1.8//源代码的兼容性级别
        sourceCompatibility = 1.8//目标字节码的兼容性级别
    }

    //打开dataBinding和viewBinding
    buildFeatures{//控制项目中特定构建功能启用或禁用的 DSL（Domain Specific Language）元素
        dataBinding = true
        viewBinding = true
    }

    //布局文件资源来源
    sourceSets {//目录指向配置
        main {
            //指定lib库目录
            res.srcDirs = [
                    'src/main/res',
                    'src/main/res/layout',
                    'src/main/res/layout/storageLayout',
                    'src/main/res/layout/fragmentUsageLayout',
                    'src/main/res/layout/mediaLayout',
                    'src/main/res/layout/imageUsageLayout',
                    'src/main/res/layout/dataBindingLayout',
                    'src/main/res/layout/espressoUsageLayout',
            ]
        }
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])//本地jar包依赖

    //testImplementation：单元测试、androidTestImplementation：仪器化测试
    //测试依赖
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test:core:1.5.0'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:rules:1.5.0'
    //Espresso：Android UI测试框架
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.5.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.5.1'
    androidTestImplementation 'com.android.support.test.uiautomator:uiautomator-v18:2.1.3'
    androidTestImplementation 'com.android.support.test.espresso:espresso-idling-resource:2.2.2'

    //MockK测试框架
    testImplementation "io.mockk:mockk:1.13.8"        // 基础库
    testImplementation "io.mockk:mockk-agent-jvm:1.13.8" // 解决某些 JDK 版本兼容性问题
    testImplementation "io.mockk:mockk-android:1.13.8"

    //Mockito测试框架
    // 添加Mockito核心库
    testImplementation 'org.mockito:mockito-core:5.2.0' // 版本号可能需要根据最新版本调整[^2]
    // 如果需要支持Android特定功能，可以添加以下依赖
    androidTestImplementation 'org.mockito:mockito-android:5.2.0'
    // 如果需要Mockito扩展功能（如Mockito Inline），可以添加以下依赖
    testImplementation 'org.mockito:mockito-inline:5.2.0'

    //远程依赖
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    //MutableLiveData依赖
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.2.0"
    implementation 'androidx.test.espresso:espresso-idling-resource:3.6.1'

    //RecyclerView布局插件
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    //卡片布局
    //noinspection GradleCompatible
    implementation 'com.android.support:cardview-v7:24.0.0-alpha1'

    //RXJava插件
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava3:2.9.0'
    //GSon插件
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    //引入glide图片加载库
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    //3D地图
//    implementation 'com.amap.api:3dmap:9.0.0'
    //定位功能
//    implementation 'com.amap.api:location:6.1.0'
    //搜索功能
//    implementation 'com.amap.api:search:9.2.0'
    //导航sdk
    implementation 'com.amap.api:navi-3dmap:9.3.0_3dmap9.3.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'

    //Room插件
    def room_version = '2.2.0-alpha01'
    implementation "androidx.room:room-runtime:$room_version"//Room的api支持
    annotationProcessor "androidx.room:room-compiler:$room_version"//Room的注释处理器

    //Material Design引用
    implementation 'com.google.android.material:material:1.0.0'

    //七牛云SDK
    implementation ('com.qiniu:qiniu-android-sdk:8.5.0'){
        exclude (group: 'com.squareup.okhttp3', module: 'okhttp')
    }
    implementation 'com.qiniu:qiniu-java-sdk:7.2.+'

    //极光厂商通道
    // 必选，此处以JPush 5.6.0 版本为例，注意：5.0.0 版本开始可以自动拉取 JCore 包，无需另外配置
//    implementation 'cn.jiguang.sdk:jpush:5.6.0'
    //不再使用自动拉取的最新版 JCore
    implementation ('cn.jiguang.sdk:jpush:5.6.0'){
        exclude group: 'cn.jiguang.sdk', module: 'jcore'
    }
    //使用指定的 JCore 版本
    implementation 'cn.jiguang.sdk:jcore:4.5.3'
    // 可选，集成极光分析SDK后，即可支持行为触发推送消息、推送转化率统计，用户行为分析和用户标签等功能
    implementation 'cn.jiguang.sdk:joperate:2.0.2'

    //厂商通道
    //JPush Android SDK 4.6.0 以上版本更新华为 HMS SDK 版本为:6.3.0.304 及
    // 以上版本,接入要求：Android Studio 3.6.1 或更高版本、Android Gradle 插件 3.5.4 或更高版本。
    implementation 'com.huawei.hms:push:6.12.0.300'

    //厂商版本和 JPush SDK 版本保持一致
    implementation 'cn.jiguang.sdk.plugin:huawei:5.6.0'
}